// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3kWG0bi6aZGk1dAmcc8SXU0VUtbiZHlo',
    appId: '1:368214688311:web:c9539a6aa12207c7da35b2',
    messagingSenderId: '368214688311',
    projectId: 'revida-d535b',
    authDomain: 'revida-d535b.firebaseapp.com',
    storageBucket: 'revida-d535b.firebasestorage.app',
    measurementId: 'G-CM5DXV8G7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0H_ULwE540EfZXkhKRX6GoB1Kb2ScqA',
    appId: '1:368214688311:android:590a953573f43397da35b2',
    messagingSenderId: '368214688311',
    projectId: 'revida-d535b',
    storageBucket: 'revida-d535b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwx6kIFHB8tL3PEkv3l8RTn47aX07q76Q',
    appId: '1:368214688311:ios:23bbac601bb01478da35b2',
    messagingSenderId: '368214688311',
    projectId: 'revida-d535b',
    storageBucket: 'revida-d535b.firebasestorage.app',
    iosBundleId: 'app.marcomendez.revida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwx6kIFHB8tL3PEkv3l8RTn47aX07q76Q',
    appId: '1:368214688311:ios:47eba20c57e95a73da35b2',
    messagingSenderId: '368214688311',
    projectId: 'revida-d535b',
    storageBucket: 'revida-d535b.firebasestorage.app',
    iosBundleId: 'app.marcomendez.revida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3kWG0bi6aZGk1dAmcc8SXU0VUtbiZHlo',
    appId: '1:368214688311:web:98d29c94024d58afda35b2',
    messagingSenderId: '368214688311',
    projectId: 'revida-d535b',
    authDomain: 'revida-d535b.firebaseapp.com',
    storageBucket: 'revida-d535b.firebasestorage.app',
    measurementId: 'G-MV0YP01LRC',
  );
}